
package frc.robot.constants;

import static edu.wpi.first.units.Units.*;

import org.ironmaple.simulation.drivesims.COTS;

import com.ctre.phoenix6.configs.*;
import com.ctre.phoenix6.swerve.*;
import com.pathplanner.lib.config.ModuleConfig;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;

import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.units.measure.*;

import frc.robot.subsystems.Swerve;
import frc.util.dataTypes.Triplet;
import frc.util.dataTypes.Tuple;
import frc.util.simulation.SwerveSim;

// Generated by the Tuner X Swerve Project Generator
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
public class DriveConstants {
    public static final double DRIVE_P = 1.5d;
    public static final double DRIVE_I = 0;
    public static final double DRIVE_D = 0.08;
    public static final Distance DRIVE_TOLERANCE = Meters.of(0.05);
    public static final double DRIVE_KS = 0;

    public static final double ROT_P = 0.03;
    public static final double ROT_I = 0;
    public static final double ROT_D = 0;
    public static final Angle ROT_TOLERANCE = Degrees.of(1.5);
    public static final double ROT_KS = 0; // 0.01 NOT APPLIED

    protected static final Distance kWheelRadius = RobotMap.IS_OASIS ? OasisTunerConstants.kWheelRadius : MirageTunerConstants.kWheelRadius;
    public static final LinearVelocity kSpeedAt12Volts = RobotMap.IS_OASIS ? OasisTunerConstants.kSpeedAt12Volts : MirageTunerConstants.kSpeedAt12Volts;
    protected static final double kDriveGearRatio = RobotMap.IS_OASIS ? OasisTunerConstants.kDriveGearRatio : MirageTunerConstants.kDriveGearRatio;

    private static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> frontLeftModule =
        RobotMap.IS_OASIS ? OasisTunerConstants.FrontLeft : MirageTunerConstants.FrontLeft;
    private static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> frontRightModule =
        RobotMap.IS_OASIS ? OasisTunerConstants.FrontRight : MirageTunerConstants.FrontRight;
    private static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> backLeftModule =
        RobotMap.IS_OASIS ? OasisTunerConstants.BackLeft : MirageTunerConstants.BackLeft;
    private static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> backRightModule =
        RobotMap.IS_OASIS ? OasisTunerConstants.BackRight : MirageTunerConstants.BackRight;

    public static final Swerve createDrivetrain() {
        return RobotMap.IS_OASIS ? OasisTunerConstants.createDrivetrain() : MirageTunerConstants.createDrivetrain();
    }

    public static final LinearVelocity MaxSpeed = kSpeedAt12Volts;
    public static final AngularVelocity MaxAngularRate = RotationsPerSecond.of(0.75);
    public static final Distance RobotWidth = Inches.of(30);
    public static final double COF = COTS.WHEELS.VEX_GRIP_V2.cof;

    public static final Time kSimLoopPeriod = Seconds.of(0.005); // faster than default for better accuracy
    @SuppressWarnings("unchecked")
    public static final SwerveSim getSwerveSim(Swerve drivetrain) {
        return new SwerveSim(
            new Triplet<Time, Mass, Double>(kSimLoopPeriod, ROBOT_MASS, COF),
            new Tuple<Distance, Distance>(RobotWidth, RobotWidth),
            new Tuple<DCMotor, DCMotor>(DCMotor.getKrakenX60Foc(1),
            RobotMap.IS_OASIS ? DCMotor.getFalcon500Foc(1) : DCMotor.getKrakenX60Foc(1)), //TODO: change to 44 once wpilib 2026
            drivetrain.getModuleLocations(),
            drivetrain.getPigeon2(),
            drivetrain.getModules(),
            frontLeftModule,
            frontRightModule,
            backLeftModule,
            backRightModule);
    }

    public static final SwerveRequest.FieldCentric fieldCentricRequest = new SwerveRequest.FieldCentric();
    public static final SwerveRequest.RobotCentric robotCentricRequest = new SwerveRequest.RobotCentric();
    public static final SwerveRequest.SwerveDriveBrake brakeRequest = new SwerveRequest.SwerveDriveBrake();
    public static final SwerveRequest.ApplyRobotSpeeds autonRequest = new SwerveRequest.ApplyRobotSpeeds();

    public static final double SLOW_MODE_MULT = 0.4;


    public static final PIDConstants TRANSLATION_PID = new PIDConstants(5, 0, 0); // TODO: Tune
    public static final PIDConstants ROTATION_PID = new PIDConstants(5, 0, 0);

    protected static final Mass ROBOT_MASS = Pounds.of(115); // TODO: Update
    private static final MomentOfInertia ROBOT_MOI = KilogramSquareMeters.of(3.3927854218);

    private static final ModuleConfig MODULE_CONFIG = new ModuleConfig(
        DriveConstants.kWheelRadius, DriveConstants.kSpeedAt12Volts,
        DriveConstants.COF, DCMotor.getKrakenX60Foc(1).withReduction(DriveConstants.kDriveGearRatio),
        Amps.of(120), 1);

    public static final RobotConfig getConfig(Translation2d... moduleLocations) {
        return new RobotConfig(ROBOT_MASS, ROBOT_MOI, MODULE_CONFIG, moduleLocations);
    }


    public static final double JOYSTICK_DEADBAND = 0.1;
    public static final int CONTROLLER_POW = 2;
    public static final double TRIGGER_DEADBAND = 0.25;
    public static final int DPAD_UP = 0;
    public static final int DPAD_RIGHT = 90;
    public static final int DPAD_DOWN = 180;
    public static final int DPAD_LEFT = 270;
    public static final int SUPPLY_CURRENT_LIMIT = 10;
    public static final boolean ENABLE_SUPPLY_CURRENT_LIMIT = true;
}
